// week10/burning-airlines-immersive/ba-react-frontend/src/components/FlightSearch.js
import React, { useState } from 'react';
import { useHistory } from 'react-router-dom';

const FlightSearch = (props) => {

  const [origin, setOrigin] = useState('SYD');
  const [destination, setDestination] = useState('MEL');
  const history = useHistory();

  const handleClick = () => {
    history.push(`/search/${origin}/${destination}`);
  };

  return (
    <div>
      <label>Origin:</label>
      &nbsp;&nbsp;
      <select onChange={(ev) => setOrigin(ev.target.value)} value={origin} >
        <option>SYD</option>
        <option>MEL</option>
        <option>SIN</option>
        <option>SFO</option>
      </select>
      &nbsp;&nbsp;
      <label>Destination:</label>
      &nbsp;&nbsp;
      <select onChange={(ev) => setDestination(ev.target.value)} value={destination} >
        <option>SYD</option>
        <option>MEL</option>
        <option>SIN</option>
        <option>SFO</option>
      </select>
      &nbsp;&nbsp;
      <button onClick={ handleClick }>Search</button>
    </div>
  );

};

export default FlightSearch;

// week10/burning-airlines-immersive/ba-vue-frontend/src/views/FlightSearch.vue
<template lang="html">
  <div>
    <h3>Flight Search</h3>

    <label for="">Origin:</label>
    <select v-model="origin">
      <option value="">Please select:</option>
      <option>SYD</option>
      <option>MEL</option>
      <option>SIN</option>
      <option>SFO</option>
    </select>
    &nbsp; &nbsp;
    <label for="">Destination:</label>
    <select v-model="destination">
      <option value="">Please select:</option>
      <option>SYD</option>
      <option>MEL</option>
      <option>SIN</option>
      <option>SFO</option>
    </select>
    &nbsp; &nbsp;
    <button v-on:click="submitSearch">Search Flights</button>

  </div>
</template>

<script>
export default {
  name: 'FlightSearch',

  data(){
    return {
      // Like initialising "state = {...};" in a React class

      // Pre-select the dropdown just for dev
      // TODO: clear for production deploy
      origin: 'SYD',
      destination: 'MEL',
    };
  }, // data()

  methods: {

    submitSearch(){
      // console.log('Button pressed!', this);
      // TODO: navigate to a new Vue route

      // NOTE: can also call with route string:
      //       this.$router.push('/search/SYD/MEL');
      this.$router.push({
        name: 'SearchResults',
        params: {
          origin: this.origin,
          destination: this.destination
        }
      });

    } // submitSearch()

  } // methods

}
</script>

<style lang="css" scoped>
</style>
